AllCops:
  TargetRubyVersion: 3.1.0
  Exclude:
    - "test/tmp/**/*.rb"

Metrics/AbcSize:
  Exclude:
    - "test/**/*_test.rb"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "test/**/*.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "test/dummy/bin/setup"
    - "test/dummy/bin/update"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false
