AllCops:
  Exclude:
    - test/generators/tmp/**/*.rb
    - test/tmp/**/*.rb
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.1.0

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "test/dummy/bin/setup"
    - "test/dummy/bin/update"

Style/StringLiterals:
  EnforcedStyle: double_quotes
